name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest-cov msgpack-python
          pytest --cov src/ahocorapy/ --cov-report=xml tests/ahocorapy_test.py
      - name: Upload coverage info to codecov
        run: |
          curl -s https://codecov.io/bash | bash
